### ISSUE TITLE
loadout not working

### ISSUE THREAD

**Issue by temar96** [After-Hours-Gaming/vanilla-issues#1]
pistols got enabled but still dont spawn with 1

**Comment by MyDimeIsUp** [comment]
Fixed https://github.com/After-Hours-Gaming/ttt/commit/1d3c5326522c7faa749de3d9b63f43cb05606c98

**Comment by MyDimeIsUp** [comment]
Fixed https://github.com/After-Hours-Gaming/ttt/commit/1d3c5326522c7faa749de3d9b63f43cb05606c98
