### ISSUE TITLE
!unrmute doesnt work

### ISSUE THREAD

**Issue by MrUnknownShadow** [After-Hours-Gaming/vanilla-issues#14]
So say I do !rmute Scotty as a mistake then I do !unrmute Scotty the command comes back as "Scotty doesn't have any active round mutes!" So they still get rmuted even if we do !unmute Scotty

**Comment by temar96** [comment]
Tried unmute as that would be normal command ,

**Comment by MyDimeIsUp** [comment]
Fixed
