### ISSUE TITLE
Unable to use Slay button in Damagelogs if person has left the server

### ISSUE THREAD

**Issue by j3kawesome** [After-Hours-Gaming/vanilla-issues#7]
Gives error (pasted below)
[ttt damagelogs] addons/ttt damagelogs/lua/damagelogs/cl_tabs/rdm_manager.lua:83: attempt to index upvalue 'ply' (a boolean value)
    1. DoClick - addons/ttt damagelogs/lua/damagelogs/cl_tabs/rdm_manager.lua:83
        2. OnMouseReleased - lua/vgui/dlabel.lua:237
            3. unknown - addons/_ahg_core/lua/vgui/dmenuoption.lua:66

**Comment by temar96** [comment]
done by dime
